version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      FLASK_DEBUG: "false" # 컨테이너에서는 false 권장
